apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-onlinebookstore
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      serviceAccountName: github-deployer
      containers:
        - name: my-container
          image: docker.io/madhavkrishna118/java-app:__IMAGE_TAG__
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: my-onlinebookstore-service
spec:
  selector:
    app: my-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
