name: CI/CD for Java App

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout Code
    - name: Checkout Code
      uses: actions/checkout@v3

    # Step 2: Set up Java
    - name: Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    # Step 3: Build the Java Application
    - name: Build with Maven
      run: mvn clean package

    # Step 4: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 5: Build and Push Docker Image
    - name: Build and Push Docker Image
      run: |
        docker build --progress=plain --no-cache -t madhavkrishna118/java-app:${{ github.sha }} .
        docker push madhavkrishna118/java-app:${{ github.sha }}
    
    # Step 6: install the oc Client
    - name: Install oc CLI and Login
      run: |
        curl -LO https://mirror.openshift.com/pub/openshift-v4/x86_64/clients/ocp/stable/openshift-client-linux.tar.gz
        tar -xvzf openshift-client-linux.tar.gz -C /usr/local/bin
        oc login --token=${{ secrets.OCP_SA_TOKEN }} --server=${{ secrets.OCP_API }} --insecure-skip-tls-verify=true
        oc project ${{ secrets.OCP_NAMESPACE }}

    # Step -7: Replace __IMAGE_TAG__ in deployment.yaml
    - name: Replace image tag in deployment.yaml
      run: |
         sed -i "s|__IMAGE_TAG__|${{ github.sha }}|g" deployment.yaml

    # Step 7: Deploy in OCP
    - name: Deploy with Dynamic PVC
      run: |
        oc apply -f deployment.yaml
        oc expose deploy my-onlinebookstore
        oc expose svc my-onlinebookstore
